### ISSUE TITLE
May i have permission to release this plugin after i fixed it?

### ISSUE THREAD

**Issue by ShatteredAtom** [nikipuh/CustomSetting#1]

**Comment by ShatteredAtom** [comment]
@nikipuh please

**Comment by nikipuh** [comment]
You can fix it and make a pull request. What do you mean by "release"?

**Comment by ShatteredAtom** [comment]
like on poggit i have made a description and all that here is a screen shot 
![screenshot 2018-01-28 at 4 26 22 pm](https://user-images.githubusercontent.com/35435955/35488012-0ccf779e-0448-11e8-8347-158ae098696e.png)

**Comment by ShatteredAtom** [comment]
@nikipuh

**Comment by ShatteredAtom** [comment]
![screenshot 2018-01-28 at 4 27 27 pm](https://user-images.githubusercontent.com/35435955/35488022-287f10e4-0448-11e8-9d75-20b3efefc373.png)

**Comment by nikipuh** [comment]
If you give Credits - sure!
